### ISSUE TITLE
Reliable way to get cover images

### ISSUE THREAD

**Issue by PKBeam** [PKBeam/AMWin-RP#1]
To get the cover image for a song, we currently do a search on Apple Music's website using the song title and artist.

This is not ideal for two reasons:

1. The search result may not have the correct cover art.
2. If the song isn't actually on Apple Music (e.g. personal library), the search may give an incorrect cover art.

Is there a way we can completely prevent these false positive and false negative cases from happening?

**Comment by iammarxg** [comment]
You could theoretically program it to take your locally stored cover art, but I'm not sure exactly how I would do it.

I wonder if it's possible to source the cover art from multiple streaming services. Might be possible.

**Comment by PKBeam** [comment]
Using locally downloaded cover art is a pretty good idea, though there are two issues:
- We need to figure out which cover art corresponds to what song (if that's even possible),
- Discord RPC expects the image as a URL, so we'd have to get the image hosted on a webserver somehow.

I think sourcing album art from other websites might be the best way to go. Maybe if Apple Music doesn't have an exact match  we can look for the cover art somewhere else.

**Comment by LiMoon** [comment]
I'm not sure how to look at musicdb, if I can use the method to parse the file, maybe can get the artwork special ID?
And the local music album pictures seem to be able to use artwork.sqlite to get the picture location?
Uploading it to Discord or Imgur?

Music\Apple Music\Apple Music Library.musiclibrary\Library.musicdb 
Music\Apple Music\Apple Music Library.musiclibrary\artwork\(*.jpeg, *.png, *.jpg)

**Comment by LiMoon** [comment]
I'm not sure how to look at musicdb, if can use the method to parse the file, maybe can get the artwork special ID?
And the local music album pictures seem to be able to use artwork.sqlite to get the picture location?
Uploading it to Discord or Imgur API?

Music\Apple Music\Apple Music Library.musiclibrary\Library.musicdb 
Music\Apple Music\Apple Music Library.musiclibrary\artwork\(*.jpeg, *.png, *.jpg)

**Comment by PKBeam** [comment]
Commit 09a41591348c24b278a151b066d7022611245ec0 allows using the Last.FM API to obtain album art if the API key is provided. 

At this point the only real improvement upon this would be to obtain the image URL directly from the Apple Music application. It seems like this would only be possible with some low-level application memory watching, which probably isn't feasible.
