### ISSUE TITLE
v1.4.3 comes up as a Trojan:Win32/Wacatac.H!ml in Win11 Defender

### ISSUE THREAD

**Issue by burdittw** [PKBeam/AMWin-RP#100]
**Version Info**
v1.4.3
US

Current version of the app popped as a Trojan in Windows 11 Defender. See image for details.

![image](https://github.com/PKBeam/AMWin-RP/assets/10444699/7783a4d9-65ba-4492-bccc-cf7db1d052c2)

**Comment by PKBeam** [comment]
I don't know if there's anything I can really do about this.

Defender's reasoning for flagging a binary is very opaque. Who knows why it thinks there's a trojan?

**Comment by sininspira2** [comment]
Ran that version through VirusTotal and nothing popped there
https://www.virustotal.com/gui/file/7ec0040b963421edbeacb0d7b023fb84277d1b1ecc4a9754626b76557f07368a/behavior

likely just a false positive from heuristic scanning. I had it running as well on windows 11 and it never popped defender.
