### ISSUE TITLE
The album cover issue in version 1.4.3.

### ISSUE THREAD

**Issue by Reynold9650** [PKBeam/AMWin-RP#101]
v1.4.3 bug

When I change the region to 'TW', the album covers display correctly, but they cannot be displayed when I play English songs.
![image](https://github.com/PKBeam/AMWin-RP/assets/149511905/b33179c5-d6b5-4804-a5f1-83860a1a5a51)

![image](https://github.com/PKBeam/AMWin-RP/assets/149511905/70c4378d-6613-47ca-9274-d800d2c5cc9e)

When I change the region to 'US', album covers display correctly when playing English songs, but they fail to display when I play non-English songs.

![image](https://github.com/PKBeam/AMWin-RP/assets/149511905/db4de19d-5e84-42fe-9c14-25b9bd5b6590)

![image](https://github.com/PKBeam/AMWin-RP/assets/149511905/b76aaf92-8842-4319-9800-708f0688191e)

[2024-04-27.log](https://github.com/PKBeam/AMWin-RP/files/15136914/2024-04-27.log)

**Comment by PKBeam** [comment]
Can you try this version here and post logs if you still have issues?

https://github.com/PKBeam/AMWin-RP/releases/download/untagged-eb9c4a843f5ef8251a2e/AMWin-RichPresence-280420241.zip

**Comment by Reynold9650** [comment]
The album cover is working properly 👍
I haven't encountered any problems at the moment.

![image](https://github.com/PKBeam/AMWin-RP/assets/149511905/80359fdf-eb2f-4c65-8f5f-1aa9cae70c0f)

![image](https://github.com/PKBeam/AMWin-RP/assets/149511905/5a76eacd-7297-4f4f-9107-e36847396c09)
