### ISSUE TITLE
Timestamps doesnt work on v1.4.3

### ISSUE THREAD

**Issue by 21mtd** [PKBeam/AMWin-RP#102]
**Version Info**
AMWin-RP v1.4.3 (region: VN)
Apple Music 1.4.6.85 (1.1030.21762.0)

**Describe the bug**
v1.4.3 broke timestamps, other features are fine.
![image](https://github.com/PKBeam/AMWin-RP/assets/75530836/59b1f804-a500-4623-90f7-6c3fc53cb6b1)

**Log Files**
![image](https://github.com/PKBeam/AMWin-RP/assets/75530836/30df555b-096f-4ffc-814e-e55374787691)

**Comment by PKBeam** [comment]
Can you try this version here and post logs if you still have issues?

https://github.com/PKBeam/AMWin-RP/releases/download/untagged-eb9c4a843f5ef8251a2e/AMWin-RichPresence-280420241.zip

**Comment by 21mtd** [comment]
> Can you try this version here and post logs if you still have issues?
> 
> https://github.com/PKBeam/AMWin-RP/releases/download/untagged-eb9c4a843f5ef8251a2e/AMWin-RichPresence-280420241.zip

link shows Not Found

**Comment by PKBeam** [comment]
Try this one?

https://github.com/PKBeam/AMWin-RP/releases/download/28042024-testing-1/AMWin-RichPresence-280420241.zip

**Comment by 21mtd** [comment]
> Try this one?
> 
> https://github.com/PKBeam/AMWin-RP/releases/download/28042024-testing-1/AMWin-RichPresence-280420241.zip

this works great so far, no error in log
