### ISSUE TITLE
AMWin doesn't work properly after update to v1.4.4.

### ISSUE THREAD

**Issue by OyeCES** [PKBeam/AMWin-RP#103]
**Version Info**
AMWin v1.4.4
Apple Music 1.4.6.85 (1.1030.21762.0)
DE

**Describe the bug**
AMWin doesn't work properly after update v1.4.4. Discord status is being displayed for a few seconds and then disappears. Also if "RP when music paused" is toggled it detects which song is playing but shows it as a discord status with paused icon. Downgraded to 1.4.0 and got it working again.

**Log Files**
[2024-04-28.log](https://github.com/PKBeam/AMWin-RP/files/15142337/2024-04-28.log)
![image](https://github.com/PKBeam/AMWin-RP/assets/165492164/712ce78c-06db-473e-b9c5-0d5f2d002a42)

**Comment by thefinerarts** [comment]
same. none of the previous "fixes" fixed the issue. also went back to 1.40.

**Comment by bgarber** [comment]
Hi!
The same happens to Last.FM scrobbling. It appears as currently playing, but the scrobble is dropped after a few seconds.

**Comment by RoGalanR** [comment]
I'm going to get the 1.4 because 1.44 beginf the scrobbling, it appears in last fm profile as "scrobbling" but then it vanishes, I don't have any scrob since april 28, and I listen to music everyday.

**Comment by heartereki** [comment]
> Hi! The same happens to Last.FM scrobbling. It appears as currently playing, but the scrobble is dropped after a few seconds.

the same is happening to me.

**Comment by PKBeam** [comment]
If you're affected by this problem, please try this build and see if it fixes it.

https://github.com/PKBeam/AMWin-RP/releases/tag/05052024-testing-1

If it doesn't work, please post logs.

**Comment by maksymilianmichta** [comment]
[2024-05-28.log](https://github.com/PKBeam/AMWin-RP/files/15487309/2024-05-28.log)
[2024-05-29.log](https://github.com/PKBeam/AMWin-RP/files/15487310/2024-05-29.log)
[2024-05-24.log](https://github.com/PKBeam/AMWin-RP/files/15487311/2024-05-24.log)
[2024-05-25.log](https://github.com/PKBeam/AMWin-RP/files/15487314/2024-05-25.log)

here are some logs each one ended in this bug , what works for me to  make it work again is : ending amw process tree and next  restarting apple music and then turning on amw again
