### ISSUE TITLE
Save credentials between version updates

### ISSUE THREAD

**Issue by sininspira2** [PKBeam/AMWin-RP#106]
I'd like to request the saving of credentials to a common/shared config file between version updates so I don't have to keep copying and pasting each time

**Comment by 21mtd** [comment]
config file is always saved for me, I just download new versions (full version) and replace the old files.

config is saved at `\AppData\Local\AMWin-RichPresence\AMWin-RichPresence_Path_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`
