### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by kaytheplug** [PKBeam/AMWin-RP#109]
It's not letting me login to my last.fm account. I keep getting an error that my credentials are incorrect, when they're not.

**Comment by LadShift** [comment]
same here 
![image](https://github.com/PKBeam/AMWin-RP/assets/172215246/6e1c29a4-c6a3-4555-806d-32bb03433398)

**Comment by PKBeam** [comment]
This app doesn't handle credential validation for Last.FM - it just sends the credentials over to the scrobbling library.

If this is a legitimate issue it needs to be raised with Last.FM or the maintainers of the scrobbling library.
