### ISSUE TITLE
Add Option to remove ` -  EP ` and ` - Single`  suffix of Album Name when scrobble to last.fm 

### ISSUE THREAD

**Issue by fikimaul** [PKBeam/AMWin-RP#11]
Hi, many streaming service does't have that ( ` -  EP ` and ` - Single` ) album name suffix.  So when i have scrobble from other streaming service, on last.fm will counted as same album.

ex :
Apple Music
![image](https://user-images.githubusercontent.com/18456011/235371521-be917016-ffbd-4aa9-aadf-156f4ee79b85.png)

Spotify : 
![image](https://user-images.githubusercontent.com/18456011/235371558-f71ee441-eaee-4c6d-8812-26e3786b29d6.png)

last.fm 
![image](https://user-images.githubusercontent.com/18456011/235371571-9b6bab30-317f-48d9-b6c8-e7936368f4e9.png)

Thank You, 🍻

**Comment by PKBeam** [comment]
fixed. will be out in next release

**Comment by fikimaul** [comment]
> fixed. will be out in next release

Thank you for your work. 👍👍

**Comment by fikimaul** [comment]
Hi @PKBeam , i think this clean song name not the album name as mention in my request. I think Song name on apple music does't have that suffix.

![image](https://user-images.githubusercontent.com/18456011/235408783-b4cf346c-ad97-420b-912e-288d1de03918.png)
