### ISSUE TITLE
Listening Status (Suggest)

### ISSUE THREAD

**Issue by hadocafes** [PKBeam/AMWin-RP#114]
**Version Info**
AMWin-RP ES (v. 1.4.5)

**Here’s a suggestion**

Maybe replace **Playing** with the new **Listening** status for the Rich Presence (https://discord.com/developers/docs/game-sdk/activities#data-models-activitytype-enum).

![Image 1](https://github.com/user-attachments/assets/e90cd9e8-5201-44aa-8489-fedbafede0b0)

**Comment by malloryhayr** [comment]
I think this would require completely rewriting AppleMusicDiscordClient to use GameSDK instead of the legacy RPC library.

**Comment by mickeida** [comment]
It is not necessary at all, it should work with Discord RPC. The "discord-rpc-csharp" library still needs to be updated. See https://github.com/Lachee/discord-rpc-csharp/issues/251

**Comment by malloryhayr** [comment]
My apologies, I wasn't aware that RPC was still receiving updates

**Comment by PKBeam** [comment]
> > [Lachee/discord-rpc-csharp#255](https://github.com/Lachee/discord-rpc-csharp/pull/255) It looks like someone submitted a pull request to add support for setting activity types, but it hasn't been reviewed for a week now.
> 
> It’s been merged, so when can we please expect a new update that includes the Listening activity? Thanks, @PKBeam :shipit:

After the newest version of the library is released to NuGet.

**Comment by PKBeam** [comment]
Will be implemented with 1.4.7 (releasing soon)

![image](https://github.com/user-attachments/assets/622cd8d2-a0f6-4228-8fc9-56849d586e30)
