### ISSUE TITLE
Last.fm only tracks when playing in playlist

### ISSUE THREAD

**Issue by Mortxn** [PKBeam/AMWin-RP#12]
As title mentions, Last.fm only tracks in playlists, not when listening to an album.

EDIT: found out it tracks when album is in library, but not when playing from browse now or in apple music "store"

**Comment by PKBeam** [comment]
please try with 1.2.0

**Comment by Mortxn** [comment]
Kind of works? It tracks way less now, but tracks without it being in the library. Also the rich presence stops after a few seconds.

**Comment by PKBeam** [comment]
can you give an example of a specific album that causes the issue and how exactly you navigated to it in the Apple Music UI?

**Comment by Mortxn** [comment]
Ah! It seems to be working now! Seemed like all i needed to do was to restart my computer (_should've thought of that haha_)
