### ISSUE TITLE
Multiple Desktop Detection

### ISSUE THREAD

**Issue by planetwiide** [PKBeam/AMWin-RP#120]
**Version Info**
1.4.5 for AMWin-RP, Apple Music 1.4.7.62 (1.1031.15873.0)
Region FR

**Describe the bug**
The app doesn't detect Apple Music when its window is in another desktop (WIN+Tab).

![image](https://github.com/user-attachments/assets/382bbe01-a865-464f-8b15-0d97321d1c3a)
In this case, my apple music is in Desktop 1 (Bureau 1) And whenever i go on any other desktops of my PC, it justs stop detecting the apple music window. It's an easy fix but a really niche issue so i think you'll have time to fix it <3

Not reported in any issues i've seen.

**Log Files**
No log files but no errors at all :/

**Comment by PKBeam** [comment]
Try this:
https://github.com/PKBeam/AMWin-RP/releases/tag/v1.4.6

**Comment by planetwiide** [comment]
Alright, thank you for being fast tho

**Comment by planetwiide** [comment]
Works perfectly, thank you !
