### ISSUE TITLE
DiscordRP set, not showing

### ISSUE THREAD

**Issue by ameasere** [PKBeam/AMWin-RP#121]
**Version Info**
Apple Music 1.4.7.62 (1.1031.15873.0)
AMWin-RP v1.4.6 configured to GB - NoRuntime version!

**Describe the bug**
AMWin-RP fails to detect AppleMusic.exe multiple times despite it being open prior to AMWin-RP running, eventually finding it. It says it sets the DiscordRP to the song playing, and nothing shows in Discord.

**Log Files**
[2024-09-07.log](https://github.com/user-attachments/files/16917689/2024-09-07.log)

**Comment by PKBeam** [comment]
does it happen on 1.4.5?

**Comment by ameasere** [comment]
> does it happen on 1.4.5?

It did, yes.

**Comment by iDinop** [comment]
Hello, I have the same problem !

**Comment by PKBeam** [comment]
> Hello, I have the same problem !

If the problem doesnt exist in 1.4.5, see https://github.com/PKBeam/AMWin-RP/releases/tag/v1.4.6

**Comment by iDinop** [comment]
> > Hello, I have the same problem !
> 
> If the problem doesnt exist in 1.4.5, see https://github.com/PKBeam/AMWin-RP/releases/tag/v1.4.6

sorry, I misread, I get this error on 1.4.6
![image_2024-09-08_161231860](https://github.com/user-attachments/assets/b520c8d6-0dcb-4998-ab1f-1522b810ee30)

**Comment by iDinop** [comment]
hello, I still have this problem even with latest version

**Comment by ameasere** [comment]
Still having issues even with the new version, even with Runtime: 

`[20:02:46] Apple Music song panel is not initialised or missing`

Even though Apple Music is open.

**Comment by PKBeam** [comment]
Are you using virtual desktops? If so, try putting AMWin-RP and Discord in the same desktop.

**Comment by Kyoobee** [comment]
using this since 1.4.7 and every version since, discord rich presence never worked. shows nothing on discord. scrobbling sometimes works sometimes doesn't, alot of the times it stops working after 2-3 songs. i have to either restart apple music, or add new API information. :/ i just want this to work perfectly but sadly it doesn't.

**Comment by ameasere** [comment]
> using this since 1.4.7 and every version since, discord rich presence never worked. shows nothing on discord. scrobbling sometimes works sometimes doesn't, alot of the times it stops working after 2-3 songs. i have to either restart apple music, or add new API information. :/ i just want this to work perfectly but sadly it doesn't.

Lucky you, at least it works for you at some point - mine never works out of the gate. No virtual desktops, nothing special - just plain old Windows.

**Comment by ameasere** [comment]
![{77370FE6-463A-4524-83F9-E920B4F96098}](https://github.com/user-attachments/assets/e05f7b71-a7bc-44c0-a132-35352f5d0ba5)
[2024-10-08.txt](https://github.com/user-attachments/files/17299296/2024-10-08.txt)

If I start AMWin-RP first, it complains it cannot find AppleMusic.exe - and if I start it afterwards, I get the same problem: Discord RP set but nothing shows on Discord.
