### ISSUE TITLE
Doesn't show DiscordRP since version 1.4.6

### ISSUE THREAD

**Issue by DieMeister** [PKBeam/AMWin-RP#122]
AMWin-RP 1.4.6
Apple Music 1.4.7.62 (1.1031.15873.0) 
AppleMusicRegion DE

DiscordRP doesn't work meaning no RP is shown. LastFM scrobbling sometimes works but is a bit unreliable. This is the case since i updated to v1.4.6 and was never a problem before

**Comment by PKBeam** [comment]
I've updated the release here - can you see if it works?

https://github.com/PKBeam/AMWin-RP/releases/tag/v1.4.6

**Comment by DieMeister** [comment]
everything seems to work now, thank you
