### ISSUE TITLE
AMWin doesn't start automatically

### ISSUE THREAD

**Issue by DieMeister** [PKBeam/AMWin-RP#126]
AppleMusic 1.4.7.62 (1.1031.15873.0)
AMWin 1.4.6 
Region DE

even though AutoStart is enabled AMWin doesn't start when Windows starts and needs to be run manually

**Comment by ujicos** [comment]
Same here, also locally installed to %AppData% and manually added to shell:startup

**Comment by PKBeam** [comment]
Does the app start normally if you double click the exe?

> Same here, also locally installed to %AppData% and manually added to shell:startup

Do other apps auto-start if you add them using this method?

**Comment by DieMeister** [comment]
it works with v1.4.8, don't know if anything was changed regarding autostart but i see this as resolved now, still, thank you
