### ISSUE TITLE
Not scrobbling with apple music is not on active desktop

### ISSUE THREAD

**Issue by shatorosas** [PKBeam/AMWin-RP#131]
Apple Music 1.4.7.62 (1.1031.15873.0)
AMWin-RP v1.4.7
MX

I'm using multiple desktops on windows 10, if the apple music instance is not on my active desktop it does not scrobble.
for example I have 2 desktops, one with my work stuff and other for personal, I often open apple music on my personal desktop play some music and switch to my work desktop, I made tests and it only scrobble while I'm at my active desktop.

**Comment by PKBeam** [comment]
Is this issue present on previous versions?

**Comment by shatorosas** [comment]
I've used v1.4.5, v1.4.6 and v1.4.7 and has been present on all of them

**Comment by PKBeam** [comment]
Please attach logs as per the issue template.

**Comment by PKBeam** [comment]
This should be fixed with 1.4.8 - try that and reopen this issue if that doesn't work.
