### ISSUE TITLE
Rich presence and scrobbling stopping

### ISSUE THREAD

**Issue by styamban** [PKBeam/AMWin-RP#132]
**Version Info**
Apple Music 1.4.7.62 (1.1031.15873.0)
AMWin-RP v1.4.7
BR

**Describe the bug**
Both Rich Presence and Scrobbling stops after a few songs and won't continue until I relaunch both Apple Music and AMWin. I was using the AMWin-RP 1.40.0 and wasn't experiencing this problem, but downloaded the new version since it featured the "Listening to" update on Discord. It seems that the bug exists for a while and it still present on the new release.

**Comment by PKBeam** [comment]
There is no way for me to investigate this without attaching logs.

**Comment by PKBeam** [comment]
Duplicate of https://github.com/PKBeam/AMWin-RP/issues/46
