### ISSUE TITLE
Virtual Desktop not detected again

### ISSUE THREAD

**Issue by planetwiide** [PKBeam/AMWin-RP#133]
**Version Info**

Apple Music 1.4.7.62 (1.1031.15873.0), region: FR, AMWin-RP = 1.4._

**Describe the bug**

It has already been reported but the bug persists on windows 11. When you're on any other windows virtual desktop (windows+tab), the app doesn't detect Apple Music window that is in another virtual desktop.

**Log Files**
No logs

**Comment by planetwiide** [comment]
And tbf it was fixed but right after downloading lastest release, it reverted

**Comment by PKBeam** [comment]
fixed with https://github.com/PKBeam/AMWin-RP/releases/tag/v1.4.8

**Comment by planetwiide** [comment]
ty bro <3
