### ISSUE TITLE
songs with edited name properties not displaying cover art and runtime

### ISSUE THREAD

**Issue by mxshxiee** [PKBeam/AMWin-RP#134]
![Screenshot 2024-09-27 080010](https://github.com/user-attachments/assets/81d6014f-6d96-4e4b-8d5d-968e8fa028c9)

**Comment by thienmartin** [comment]
+1

**Comment by PKBeam** [comment]
Duplicate of https://github.com/PKBeam/AMWin-RP/issues/129
