### ISSUE TITLE
New scrobbling bug with mini player after 1.4.8 update

### ISSUE THREAD

**Issue by CameronB7** [PKBeam/AMWin-RP#136]
**Version Info**
Apple Music 1.5.0.152 (1.1280.38913.0)
AMWin 1.4.8
AM Region GB

**Describe the bug**
I've noticed a new issue where RP cuts out, along with scrobbling, after about ten seconds when using the mini player. This would be a very minor thing if it weren't for the fact that it was the only reliable way I knew to make sure songs got scrobbled. It seems as though, assuming the other scrobbling bug isn't in effect, that scrobbling and RP will continue when the mini player is closed, if that helps.

**Comment by pwjmi** [comment]
having the exact same issue. ive given up and have just resorted to using open scrobbler

**Comment by CameronB7** [comment]
> having the exact same issue. ive given up and have just resorted to using open scrobbler

I didn't know this existed. It's huge for me regardless because I listen to vinyl and this feels like a way better solution to having Apple Music play the album silently. Still have my fingers crossed for this app though

**Comment by PKBeam** [comment]
Please follow the template for creating issues

**Comment by CameronB7** [comment]
I edited the comment adding version info, but I couldn't find any relevant logs to attach

**Comment by PKBeam** [comment]
This is due to a recent Apple Music modifying the UI layout.  
Will be fixed in the next release.

**Comment by PKBeam** [comment]
Fixed in [1.4.9](https://github.com/PKBeam/AMWin-RP/releases/tag/v1.4.9)
