### ISSUE TITLE
Scrobbling stops when using the search bar

### ISSUE THREAD

**Issue by shad0wuk** [PKBeam/AMWin-RP#139]
**Version Info**
Apple Music 1.5.0.152 (1.1280.38913.0) AMWin-RP v1.4.8
Region GB

**Describe the bug**
Scrobbling stops when using the search bar.
"Apple Music song panel is not initialised or missing"

**Log Files**
[2024-10-06.log](https://github.com/user-attachments/files/17271144/2024-10-06.log)

**Comment by PKBeam** [comment]
This is most likely the same issue as https://github.com/PKBeam/AMWin-RP/issues/105
