### ISSUE TITLE
not setting RP

### ISSUE THREAD

**Issue by MoSiren1** [PKBeam/AMWin-RP#142]
**1.4.9**

Program is not setting RP on my discord. Is the due to I am using Canary?

[2024-10-16.log](https://github.com/user-attachments/files/17390844/2024-10-16.log)
![image](https://github.com/user-attachments/assets/c3bfafc2-fa68-488f-9dcc-140ffd993795)

**Comment by PKBeam** [comment]
The logs indicate the RP is being set correctly. Try normal Discord and reopen if the issue persists.
