### ISSUE TITLE
When album title is only one character, Rich Presence stop updating

### ISSUE THREAD

**Issue by momizi06** [PKBeam/AMWin-RP#145]
**Version Info**
AMWin-RP: v1.4.9
region: JP

**Describe the bug**
When start listening songs that album title is only one character, Rich Presence stop updating until start playing other songs that album title is not one character.
I found this bug in these album:
- [Y](https://music.apple.com/jp/album/y/1764265950)
- [A](https://music.apple.com/jp/album/a/1536356339)
- [あ](https://music.apple.com/jp/album/%E3%81%82/1531997921)

**Log Files**
[2024-10-17.log](https://github.com/user-attachments/files/17434888/2024-10-17.log)

**Comment by Quants0** [comment]
This is happening to me too. It still scrobbles to last.fm but rich presence doesn't work.

**Comment by PKBeam** [comment]
same issue as https://github.com/PKBeam/AMWin-RP/issues/143
