### ISSUE TITLE
Not scrobbling repetead songs

### ISSUE THREAD

**Issue by rodolfonb** [PKBeam/AMWin-RP#16]
Hi!

I just installed and while testing I realized that, if I listen to a song more than once, it only scrobbles the first listen. Is there any way to fix this?

Thanks for the work!

**Comment by spedinfargo** [comment]
Unfortunately, that's a limitation of the (rather simplistic) Scrobbling part of this project.  It doesn't actually look at time elapsed and time remaining - only a simple flag of "has song changed" every five seconds.  So if the song repeats back-to-back, this never happens.  I took a look at some of the logic in official Scrobblers but haven't really dug into what it would take to add better logic.

**Comment by rodolfonb** [comment]
I have a limited knowledge so I don't know if that's something you could use in this sense but the Apple Music app has a play count for each song. So maybe checking if the play count changed could help with that.

**Comment by PKBeam** [comment]
For us to be able to read a UI element, it needs to be directly visible in the window. So we can't use the play count.

Since we have access to song progress, I think we could implement a simple check - if the song goes from >95% progress to <5% the next time we check, we can probably reset the scrobble.

**Comment by rodolfonb** [comment]
That makes sense. Hope it works!

**Comment by Lucas11925** [comment]
i've been struggling with that as well, hope they find a solution soon!

**Comment by raydiantly** [comment]
only thing keeping me from switching to the app from the website, i listen to repeated songs a lot. hope this gets fixed soon
