### ISSUE TITLE
Support for ListenBrainz

### ISSUE THREAD

**Issue by Viktini** [PKBeam/AMWin-RP#17]
ListenBrainz is a listen tracker much like last.fm, but is run by the same organisation behind MusicBrainz. It's open-source and might be easy to implement - the accounts are linked with MusicBrainz but only a user-specific token is used for authentication right now rather than needing an API key like last.fm apps do.

While there are AM scrobblers for ListenBrainz on Mac, there aren't any scrobblers on Windows, so it'd be nice to have ListenBrainz support implemented here. I'll look at implementing it myself when I can, or providing help if others intend to. I've helped out with ScrobblerBrainz, which is a plugin for MusicBee that supports ListenBrainz.

[ListenBrainz API](https://listenbrainz.readthedocs.io/en/latest/users/api/index.html)

**Comment by N-E-N** [comment]
Yea this would be great!

**Comment by PKBeam** [comment]
this will be implemented in the next update.

a beta build can be found here: https://github.com/PKBeam/AMWin-RP/releases/tag/v1.3.0b1
