### ISSUE TITLE
Doesnt work at all

### ISSUE THREAD

**Issue by buttonzero** [PKBeam/AMWin-RP#18]
downloaded both noruntime and the other version and neither work, rich presence dont show up
idk if has to do with my .net but ive tried everything and have no idea what to do, restarted my computer twice and used older versions too

**Comment by TastelessTacos** [comment]
Did you download the new update for Apple Music Preview app? That could be the reason because it stopped working for me as well.

**Comment by buttonzero** [comment]
> Did you download the new update for Apple Music Preview app? That could be the reason because it stopped working for me as well.

Yeah just downloaded it for the first time still aint working

**Comment by gustavocubas** [comment]
Aye, can confirm then newest updated broke the app again.

**Comment by PKBeam** [comment]
fixed with v1.2.2
