### ISSUE TITLE
I can’t make it work 

### ISSUE THREAD

**Issue by ZamingUwU** [PKBeam/AMWin-RP#21]
I’ve downloaded the v1.2.2 and nothing is displayed in discord im using windows 10 and the Apple Music app from Microsoft I’ve also downloaded the v1.2.1 and it didn’t worked too the app is in the background and I can open it it’s just the discord rich presence side that isn’t working Nice app btw

**Comment by ZamingUwU** [comment]
Last fm too isn’t registering the song I listen too

**Comment by Evelunes** [comment]
Hello, I've been having the same problem, so I just comment under this instead of opening a new issue.
I don't know if it's supposed to be detected instantly by discord but I added it manually and the songs playing are not showing.

![image](https://github.com/PKBeam/AMWin-RP/assets/138450191/0e3ed66d-6ff6-4726-8417-d7b4eb80c41b)

**Comment by Evelunes** [comment]
> This may seem like a dumb question, but how are you running the program? And have you updated your Apple Music from the Microsoft Store to the latest version?

Personnally I uninstalled and installed the app over the Microsoft store multiple times to try and make it work, today it’s up to date and the AM rich presence is running but not showing over discord. (I also tried reinstalling it multiple times)

**Comment by firminsurgithub** [comment]
Same issue here 👋

**Comment by Otus9051** [comment]
Same here.

**Comment by ZamingUwU** [comment]
Yes I’ve updated the Apple Music app from the Microsoft store and Discord I’ve retried with the 1.2.3 and it’s still not working.I’m using the file manager in windows to open the app pls helppp

**Comment by ZamingUwU** [comment]
Missclick my bad

**Comment by ZamingUwU** [comment]
And even tho the option is on I’m pretty sure the app doesn’t run automatically

**Comment by ZamingUwU** [comment]
Pls helps guys
