### ISSUE TITLE
Option to scrobble only the primary artist 

### ISSUE THREAD

**Issue by cillyk** [PKBeam/AMWin-RP#3]
In last.fm it is not standard to scrobble multiple artists using & as apple music likes to do, I personally prefer to just scrobble based on the first artist, I will probably make a fork and give it a shot myself but if anyone wants to give it a shot to save me the effort of setting up a dev space for C# it can be done using rejex with:

for just 2 artists:
`\ &(.*)`

ones seperated by comas:
`\ ,(.*)`

**Comment by spedinfargo** [comment]
That should be do-able.  I'll dust off the Regex skills and give it a shot later this week.  I'll also see how the official Scrobbler handles it with iTunes.  Do you have a specific song or two that I could use as an example?

**Comment by cillyk** [comment]
[https://github.com/PKBeam/AMWin-RP/pull/6](url)

**Comment by cillyk** [comment]
Added a approach to doing this to my own fork if anyone wants me to build it for them let me know.

**Comment by PKBeam** [comment]
You can separate artists by querying the Apple Music website.

For example,
![image](https://user-images.githubusercontent.com/18737124/235363420-690d3a54-3862-4db2-a188-4572653b464c.png)

**Comment by PKBeam** [comment]
implemented in commit 8237b3ce4d92daf250ef859a45a6052314db4ce3
