### ISSUE TITLE
changing text when hovering over image

### ISSUE THREAD

**Issue by raydiantly** [PKBeam/AMWin-RP#30]
it would be great if there was a setting in the app to choose whether it shows the song or album when hovering over the cover in the discord presence. currently it seems to only show the song name.

being able to enable/disable the small apple music icon would also be appreciated

**Comment by PKBeam** [comment]
> it would be great if there was a setting in the app to choose whether it shows the song or album when hovering over the cover in the discord presence. currently it seems to only show the song name.

This was changed to album name in #24.

> being able to enable/disable the small apple music icon would also be appreciated

There is a checkbox setting for this already.
