### ISSUE TITLE
Can't scrobble songs with '&'

### ISSUE THREAD

**Issue by willzus** [PKBeam/AMWin-RP#32]
I've tried different combinations and it doesn't seem to scrobble any song that contains '&'.

![image](https://github.com/PKBeam/AMWin-RP/assets/91130641/6a65b9e8-c109-4eeb-8ea6-1bd43012f34b)

![image](https://github.com/PKBeam/AMWin-RP/assets/91130641/830f137f-ef35-49fe-ae9c-beb42d0e3d72)
 
Though, in the discord presence seems normal but no artwork.

![image](https://github.com/PKBeam/AMWin-RP/assets/91130641/9642f58f-4900-4c9f-ab75-79cb4187bfc3)

**Comment by PKBeam** [comment]
fixed in release v1.2.3
