### ISSUE TITLE
Support Apple Music play button display text in different languages

### ISSUE THREAD

**Issue by Ezyne23** [PKBeam/AMWin-RP#35]
For versions 1.2.2 and 1.2.3, I've noticed the Rich Presence for Apple Music will not disappear when I have music paused. This is mildly infuriating because it's given people the impression I'm not listening in VCs and whatnot when nothing is even playing.

I've noticed it seems like it doesn't even pick up if it's paused or not, and thus will not trigger for it to leave

DEVICE DETAILS:
Using Windows 11 with AMRichPresence (tested 1.2.2 and 1.2.3, Runtime and NoRuntime releases for both), Apple Music Preview from Microsoft Store, and latest version of Discord

STEPS TO RECREATE:
Unknown, cannot find source cause

IMAGE EXAMPLE:
![image](https://github.com/PKBeam/AMWin-RP/assets/134811348/b2665d0c-91ca-424b-8a70-5b30855e3dd6)

**Comment by PKBeam** [comment]
Try turning off “RP when music paused”

**Comment by Ezyne23** [comment]
> Try turning off “RP when music paused”

That was my original settings, it just leaves it on; I simply have it on in the screenshot to show how it's not pausing

![image](https://github.com/PKBeam/AMWin-RP/assets/134811348/e66ae968-a9c0-4b9b-8fc7-2623f2589c15)

**Comment by fl4shback** [comment]
I am wrong to assume it could come from this line ?
https://github.com/PKBeam/AMWin-RP/blob/479d302e9bcc05308adf596d592784ea67e9b4e8/AMWin-RichPresence/AppleMusicClientScraper.cs#L222

I'm using Apple Music in french so the button is called "Lecture" and not play.
What's your system language OP ?

**Comment by Ezyne23** [comment]
I've stopped using this a few months ago, but you are likely on the right track as my AM Language and System Language are both Japanese, and thus my "Play" would instead be "再生"

**Comment by PKBeam** [comment]
Probably will have to hardcode lookups for this, as there seems to be no other differences in button state (from the UIA API) besides the text name.

**Comment by PKBeam** [comment]
this hopefully will be fixed in 1.4.1 with a fallback option that determines if the song was paused based on the last known timestamps.

**Comment by fl4shback** [comment]
Just tried and it looks like it's working, thanks for the fix !
