### ISSUE TITLE
Add song link button to rich presence

### ISSUE THREAD

**Issue by SpaceCypher** [PKBeam/AMWin-RP#38]

**Comment by PKBeam** [comment]
Is this actually possible? As far as I'm aware you can't embed hyperlinks in RPC images.

**Comment by nattadasu** [comment]
I don't think that's possible, unless OP wanted a way/method for other user to launch to Song/Album link in web, then the only option is button, similarly what Cider did as following screenshot:

![image](https://github.com/PKBeam/AMWin-RP/assets/49780229/7b216c8f-8fd1-453a-ad2f-af60668a1004)

**Comment by PKBeam** [comment]
implemented with #81
