### ISSUE TITLE
Serious problem when scrobbling classical music

### ISSUE THREAD

**Issue by mintybluevk** [PKBeam/AMWin-RP#41]
When scrobbling classical music from apple music.AMwin will ignore the  artist but scrobble the composer(which I think is fine)but it will add "BY" in front of the composer's name.
As a result it will create an artist name using the added"BY" in front on last.fm.This defnitely needs a fix.

![微信图片_20230908060618](https://github.com/PKBeam/AMWin-RP/assets/144393477/03819b0f-535d-4471-b22c-10b067b3d625)

**Comment by PKBeam** [comment]
Will be fixed with v1.2.5.

Also added an option to choose between composer and performer for purposes of RP display and scrobbling.
