### ISSUE TITLE
amrp not being seen by discord. 

### ISSUE THREAD

**Issue by Jaywin001** [PKBeam/AMWin-RP#45]
idk it just doesnt appear in discord. help pls.

**Comment by franblackcat** [comment]
same here. the latest version (v1.2.4) doesnt seem to work as well

**Comment by mario-carmo** [comment]
v1.2.4 is working here. you may need to get a new last.fm api key for it.

**Comment by NamanOG** [comment]
Not Showing in Discord

**Comment by NamanOG** [comment]
> idk it just doesnt appear in discord. help pls.

Get the new version, it will appear
Link for new version - [v1.2.4](https://github.com/PKBeam/AMWin-RP/releases/tag/v1.2.4)

**Comment by ShawnMayer** [comment]
Apple Music 1.4.2.35 and AMWin RP v1.2.4 / doesn't work still... help me plz

**Comment by TZNR316** [comment]
Same

**Comment by PKBeam** [comment]
Will be fixed in v1.2.5 (364d4aa4e68a6c5f577431d490e591c8a5410055)
