### ISSUE TITLE
AMWin-RichPresence-v1.2.4-NoRuntime.zip is being detected as a Trojan by Windows 11

### ISSUE THREAD

**Issue by yoloswaggerboy69** [PKBeam/AMWin-RP#48]
![Screenshot 2023-09-24 160239](https://github.com/PKBeam/AMWin-RP/assets/18366729/a111957d-2ca8-4c63-9b7f-55b681491938)

**Comment by PKBeam** [comment]
Unfortunately there's not much I can do about this. Virus detection software will never be perfect.

My Windows 11 install does not have any issues with the executable or zip.

![image](https://github.com/PKBeam/AMWin-RP/assets/18737124/6aab4330-e1ab-43b5-978a-13a621371221)
