### ISSUE TITLE
Scrobbler has stopped working today

### ISSUE THREAD

**Issue by djolep111** [PKBeam/AMWin-RP#49]
Scrobbler has stopped working today. It used to work after 1.2.4 update but now its not working at all and its not showing Discord RP too. I tried getting new API key too and it does not help

**Comment by 123lain** [comment]
same. it works for one scrobble and then nothing, is the new AM Preview update at fault?

**Comment by djolep111** [comment]
> same. it works for one scrobble and then nothing, is the new AM Preview update at fault?

I think so. It happened before after new AM Preview updates

**Comment by PKBeam** [comment]
Will be fixed in v1.2.5 (https://github.com/PKBeam/AMWin-RP/commit/364d4aa4e68a6c5f577431d490e591c8a5410055)
