### ISSUE TITLE
Can't open the app to make changes to settings and add last.fm creditionals

### ISSUE THREAD

**Issue by FCBMJ** [PKBeam/AMWin-RP#57]
App works correctly with discord and shows what songs I'm listening to but refuses to open. What am I missing?

**Comment by PKBeam** [comment]
Are you trying to open it from the toolbar? 

![image](https://github.com/PKBeam/AMWin-RP/assets/18737124/b2eeb233-a704-4fc4-aa9d-956bd5818b70)
