### ISSUE TITLE
Does not show on Discord Rich Presence or scrobble to last.fm on Win 10

### ISSUE THREAD

**Issue by Annis3110** [PKBeam/AMWin-RP#61]
I'm using the Windows 10 Pro Education Version 22H2 (OS Build 19045.3693). I've tried using both AMWin-RP and a app called AMRPC available on Microsoft Store but neither of these work to show on Discord or scrobble(AMRPC has the option to scrobble too). I'm using the latest version on Apple Music Preview, AMWin-RP, AMRPC and Discord but none of the softwares work sadly. I have a proper subscription of Apple Music so yeah. Also whenever i increase or decrease volume by using keyboard shortcuts, the pop-up shows proper info of the song being played so yeah it's not like Win does not detect songs being played either. I've tried restarting Windows, uninstalling and reinstalling all the softwares but nothing works. Any sort of help as to whether i'm doing anything wrong or something like that would be very helpful. Thanks in advance.

**Comment by sarahdumby** [comment]
Its not really working with the most recent apple music updates, just gonna have to wait for PKBeam to update it.

**Comment by PKBeam** [comment]
what Apple Music version?

1.4.3.34 works fine for me on the latest AMWin-RP build. There does not appear to have been any significant UI changes since 1.4.2.35.

**Comment by Annis3110** [comment]
im using 1.4.3.34 the same version you're using but it still does not work sadly
i used the 63 MB zip in the releases section
could it be because im using win 10?

**Comment by PKBeam** [comment]
It should be fine on Windows 10, but I can't say for sure since I'm on 11.

Please try again with the 1.2.6 release and post logs here if that still doesn't work.
