### ISSUE TITLE
While running Discord Stable with Apple Music 1.4.3.34, AMWin-RP doesn't work

### ISSUE THREAD

**Issue by Loganbogan9** [PKBeam/AMWin-RP#62]
I saw a few other reports of incompatibility, but I thought I could be a little more thorough. I'm currently running Discord stable 247929 alongside Apple Music 1.4.3.34 on Windows 11. When using AMWin-RP it failed to set a status. 
I've tried reinstalling Apple Music, .net runtime, and AMWin-RP with no success. 
![AMWin](https://github.com/PKBeam/AMWin-RP/assets/76670334/1fe874a9-4c5d-4a6c-99d6-55e22fb8f366)

If there is any other information that could be given to help, I'd be more than willing to give it. I have also tested the software on a clean install of windows with no success as well.

**Comment by BrayanOfficiel** [comment]
same here, just installed it

**Comment by emslima** [comment]
same here, just installed it now...

**Comment by PKBeam** [comment]
There was a bug on master with accidentally commented out code. 
If you were building directly from master, pull now and it should be fixed.

The prepackaged 1.2.5 release binaries are not affected by this - if you were using these then sadly I'm unable to reproduce the issue on my end even with a fresh install.

**Comment by PKBeam** [comment]
The Discord RP is set to the `AppleMusicInfo` object shown on the next line, e.g. 
```
[19:27:30] Set Discord RP to:
[AppleMusicInfo] BLEED by The Kid LAROI on THE FIRST TIME
| Duration:  169 sec
| Album art: https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/46/26/10/46261095-a39c-9231-7d1c-9718aa092b3a/196871605403.jpg/96x96bb-60.jpg
```

Can you try again with [this build](https://github.com/PKBeam/AMWin-RP/releases/download/v1.2.6.1/AMWin-RichPresence-v1.2.6.1a.zip) and post the log output?

**Comment by Loganbogan9** [comment]
So turns out I was completely wrong. It turns out in "Activity Privacy" within Discord I had disabled "current activity as a status message" I cannot confirm this is the case for everyone but for me it had nothing to do with the app and was actually my account settings. So the app itself now works fine. What threw me off was that games would still display themselves as active in Discord, however the app never would. Sorry for my simple oversight, and kudos for making this piece of software.

**Comment by Loganbogan9** [comment]
> Thanks for reporting back. Will add this to the README.

Awesome. Sorry again for missing such an obvious troubleshooting bit!
