### ISSUE TITLE
While having the AMRP with AM 1.4.3.34 cover art doesn't work and time stamps are unstable.

### ISSUE THREAD

**Issue by pierrebbourne** [PKBeam/AMWin-RP#63]
![Screenshot 2023-12-01 001328](https://github.com/PKBeam/AMWin-RP/assets/152567730/e3fbab57-08fc-4d78-96ba-788a1b01e153)
The Cover art of the ablum or single does not appear and just gives me the AM logo and I have tried everything and nothing works. The time stamps also has to be hovered over inorder for the RP to even register it. Some times the whole RP sometimes doesn't work or detect AM. Different versions of the same RP doesn't work and I can't seem to make it work how it is expected to or how it was supposed to.

**Comment by PKBeam** [comment]
Please try again with the 1.2.6 release.
