### ISSUE TITLE
Now Playing scrobbles?

### ISSUE THREAD

**Issue by hexadiver** [PKBeam/AMWin-RP#7]
Could the scrobbler implementation send a "Now Playing" scrobble of the song youre currently listening to to lastfm?

**Comment by nattadasu** [comment]
+1 with this. Also, I noticed if the app scrobbled a song too fast? It scrobbles at around ~30 secs at the beginning of song.

Maybe, just maybe, it'll be great if the scrobbling features follow Discord's progress, as user may able to modify param easily?

**Comment by th0mk** [comment]
Made a pull request: https://github.com/PKBeam/AMWin-RP/pull/56
