### ISSUE TITLE
Add search for current playing song button on Apple Music

### ISSUE THREAD

**Issue by GlxryX** [PKBeam/AMWin-RP#72]
Add a button allowing for searching on Apple Music and Spotify
<img width="299" alt="Screenshot 2023-12-28 at 1 54 24 PM" src="https://github.com/PKBeam/AMWin-RP/assets/77895395/d4d6a22f-883e-4774-8457-d9cbbb9998f0">

**Comment by PKBeam** [comment]
Duplicate of #38
