### ISSUE TITLE
Can't read Apple Music status when switched to another virtual desktop

### ISSUE THREAD

**Issue by logic** [PKBeam/AMWin-RP#73]
When the Apple Music client is open on the current virtual desktop, discord status is updated appropriately. Within a second or two of switching to another virtual desktop (ctrl-win-left/ctrl-win-right), the Apple Music discord status disappears (probably because AMWin-RP can't see details about the Apple Music app anymore).

I have no idea if there's a reasonable fix for this (I don't know what options UI Automation gives you for crossing virtual desktop boundaries), but even if it's not easily fixed, it's probably worth mentioning in the readme somehwere.

**Comment by logic** [comment]
Also: clicking "task view", right-clicking on Apple Music and selecting "Show windows from this app on all desktops" allows AMWin-RP to work consistently, which is how I narrowed down what was happening here. :)

(So, there's a workaround, at least.)

**Comment by PKBeam** [comment]
Possibly could be fixed by switching to UIA3 from FlaUI: https://github.com/FlaUI/FlaUI

**Comment by PKBeam** [comment]
Next update will fix this issue by directly querying process name and ID instead of iterating through desktop windows.

A beta build can be found here: https://github.com/PKBeam/AMWin-RP/releases/tag/v1.3.0b1

**Comment by logic** [comment]
Ah, works perfectly, thank you!
