### ISSUE TITLE
NullReferenceException in `GetAppleMusicInfo` in 1.3.0b1

### ISSUE THREAD

**Issue by SWiegandt** [PKBeam/AMWin-RP#75]
**Version Info**
1.3.0b1

**Describe the bug**
I'm intermittently getting
```
[04:55:26] Something went wrong while scraping: System.NullReferenceException: Object reference not set to an instance of an object.
   at AMWin_RichPresence.AppleMusicClientScraper.GetAppleMusicInfo()
   at AMWin_RichPresence.AppleMusicClientScraper.Refresh(Object source, ElapsedEventArgs e)
[05:49:55] Previous message repeated 653 times
```
using the latest beta, which I'm guessing has to do with the change in automation library. After getting the error once it seems to keep happening until restarting Apple Music (restarting AMWin-RP doesn't help), and I haven't been able to narrow down what causes it to start. Is it possible to log a more granular error message saying exactly what line reports the error?

**Comment by SWiegandt** [comment]
One way of triggering it is opening the properties popup window for a song, so I'm guessing there are some assumptions made about the active AM window somewhere that breaks when the active window isn't the main one?

**Comment by PKBeam** [comment]
seems to be an issue with the descendant iteration of the UI library: https://github.com/FlaUI/FlaUI/issues 
can probably make a workaround for this.

**Comment by PKBeam** [comment]
implemented a manual BFS for descendant nodes - this should fix the problem.

**Comment by SWiegandt** [comment]
Seems to be working 👍
