### ISSUE TITLE
Can't authenticate credentials

### ISSUE THREAD

**Issue by SDavies-OSM** [PKBeam/AMWin-RP#78]
**Version Info**
Apple Music v1.4.4.33
AMWin-RP v1.2.6.3

**Describe the bug**
After entering username and password and clicking 'save credentials' it states an error 'The Last.FM credentials could not be authenticated. Please make sure you have entered the correct username and password, and that your account is not currently locked' with no delay between clicking and the error message appearing. I've double checked my account is not locked and that I'm entering the correct password.

**Comment by SWiegandt** [comment]
Did you create an API account and input an API key and secret as described under https://github.com/PKBeam/AMWin-RP#lastfm-scrobbling? What you're describing seems to be what happens if you leave those fields empty.

**Comment by SDavies-OSM** [comment]
Ah. I missed that. Thank you.
