### ISSUE TITLE
NRE while scraping

### ISSUE THREAD

**Issue by j10a1n15** [PKBeam/AMWin-RP#80]
**Version Info**
AM: 1.4.4.41 (1.1028.10497.0)
RP: v1.3.0b1

**Describe the bug**
> A clear and concise description of what the bug is.

I'm not quite sure what to say, the logs should explain that there is an issue with scraping,
which makes the RPC not work :shrug:

> Have the symptoms of this bug already been reported in another issue? 

no

**Log Files**
[2024-02-09.log](https://github.com/PKBeam/AMWin-RP/files/14227221/2024-02-09.log)
[2024-02-10.log](https://github.com/PKBeam/AMWin-RP/files/14227222/2024-02-10.log)

**Comment by PKBeam** [comment]
can you open task manager and show the name of the Apple Music exe here?

**Comment by j10a1n15** [comment]
> can you open task manager and show the name of the Apple Music executable, as below?
> 
> ![image](https://private-user-images.githubusercontent.com/18737124/303803919-a9b6deb0-3176-4aac-9204-4e051395be9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MzQ0MjEsIm5iZiI6MTcwNzczNDEyMSwicGF0aCI6Ii8xODczNzEyNC8zMDM4MDM5MTktYTliNmRlYjAtMzE3Ni00YWFjLTkyMDQtNGUwNTEzOTViZTlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDEwMzUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxMjU0OTEwODQ4ODRmZjZmNzMxMzZkYTg1ZDU5ZjNjZTJmMzUxZjM5NWNhMTg5Y2I5MTYwYjVmZDk5YzBiYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vexm7G4QAvT4yK12pxkypekC0ivHZCe5WOCrNWuDYzk)

![image](https://github.com/PKBeam/AMWin-RP/assets/45315647/f31444c0-6001-4876-addf-7222fd42300a)
sorry for the late response mb

**Comment by j10a1n15** [comment]
Updated to v1.3.0 and seems to work now, ty!
