### ISSUE TITLE
Discord stops detect music if minimize Apple Music with MiniPlayer

### ISSUE THREAD

**Issue by 21mtd** [PKBeam/AMWin-RP#83]
**Version Info**
Apple Music Preview version 1.4.4.41 (1.1028.10497.0)
AMWin-RP v1.3.0

**Describe the bug**
Basically this bug only occurs if switching to MiniPlayer feature of Apple Music Preview.

1. Switch to MiniPlayer (Ctrl+Shift+M, MiniPlayer window is focused), Discord RP dropped, it will appear again if select Apple Music main window.
2. If minimize Apple Music window (with MiniPlayer window), Discord RP dropped, until Apple Music window is focus.
3. If select MiniPlayer window, Discord RP dropped (without minimize Apple Music window like Case 2)

Close MiniPlayer makes everything work normally.

**Log Files**
Whenever Discord RP dropped, this message shows up in log

`Apple Music song panel (TransportBar) is not initialised or missing`

![image](https://github.com/PKBeam/AMWin-RP/assets/75530836/c9312bee-aad4-4d6e-ae96-4f92936e0c8f)

**Comment by 21mtd** [comment]
updated post

**Comment by PKBeam** [comment]
fixed with [55c965d](https://github.com/PKBeam/AMWin-RP/commit/55c965d2f1bcea85479879f7444ea00310b889a8)
