### ISSUE TITLE
Artist name is inconsistent if there is more than one artist and the artist only subtitle option is chosen

### ISSUE THREAD

**Issue by hassiexx** [PKBeam/AMWin-RP#84]
**Version Info**
Apple Music 1.1028.10497.0
AMWin-RP 1.3.0

**Describe the bug**
When a song has multiple artists attributed, choosing the artist only subtitle option will display {main artist}, various artists. However if the artist + album subtitle option, then the artist is correctly displayed as attributed on the song.

Here is an example of a song:
![image](https://github.com/PKBeam/AMWin-RP/assets/38690898/2bf3cebb-7b48-46a0-93c7-5b6992f50781)

If Artist + Album is chosen, then the correct artist name is displayed:
![image](https://github.com/PKBeam/AMWin-RP/assets/38690898/c98346b1-0c4a-4800-809f-5cc5f1a08fa1)

However, if the artist only option is chosen, then the artist name displays the first artist and 'various artists'
![image](https://github.com/PKBeam/AMWin-RP/assets/38690898/2e3f8e5b-21e8-489c-8ba8-7492ef354268)

**Comment by PKBeam** [comment]
fixed in 673d3ce
