### ISSUE TITLE
Unable to get to Settings Screen

### ISSUE THREAD

**Issue by DaGamerJayJ** [PKBeam/AMWin-RP#93]
**Version Info**
AM 1.4.6.84, AMWINRP 1.4

**Describe the bug**
Not sure if this is a bug or not but Im unable to see this screen, as shown in the README file, to be able to customize my settings
![image_2024-04-03_210118857](https://github.com/PKBeam/AMWin-RP/assets/165980562/e1d78299-0823-4a98-832c-12076e388ab7)

**Comment by Lauraelaine91** [comment]
Click the Cider button, then go to plugin, there should be a pop up window. Do not click settings from the Cider menu

**Comment by PKBeam** [comment]
It’s in the taskbar.
