### ISSUE TITLE
Generates Many scrobbles for 1 Listen

### ISSUE THREAD

**Issue by CharlieNayler** [PKBeam/AMWin-RP#94]
V-1.4

As stated in the title, everytime I listen to a song it generates 15-20 scrobbles of the one song listen

**Comment by CharlieNayler** [comment]
eg. ![image](https://github.com/PKBeam/AMWin-RP/assets/94146265/07fd2b18-6a81-4a81-859e-8653cd5e8f0a)

**Comment by PKBeam** [comment]
same problem as #52
