### ISSUE TITLE
AMWin doesn't work on the new v1.4.1 update

### ISSUE THREAD

**Issue by 21mtd** [PKBeam/AMWin-RP#97]
**Version Info**
AMWin-RP v1.4.1
Apple Music 1.4.6.85 (1.1030.21762.0)

**Describe the bug**
AMWin doesn't work after update to v1.4.1. No discord status.

I tried downgraded to v1.4.0 and it works fine.

**Log Files**
![image](https://github.com/PKBeam/AMWin-RP/assets/75530836/0ffc88af-a9fc-4035-93c9-13cb7119b370)

**Comment by DexterKray** [comment]
I have the exact same issue. Downgrading fixes the issue

**Comment by PKBeam** [comment]
fixed with https://github.com/PKBeam/AMWin-RP/releases/tag/v1.4.2

**Comment by 21mtd** [comment]
it's working. Thanks for the hotfix

**Comment by 21mtd** [comment]
![image](https://github.com/PKBeam/AMWin-RP/assets/75530836/7cf4a595-0458-4ea1-a80d-363e78843651)

**Comment by PKBeam** [comment]
redownload the 1.4.2 release - i pushed a small change to it that should fix timestamps
