### ISSUE TITLE
Album cover is not displaying

### ISSUE THREAD

**Issue by Reynold9650** [PKBeam/AMWin-RP#98]
Album cover is not displaying

![image](https://github.com/PKBeam/AMWin-RP/assets/149511905/7c0155d7-291d-4ed6-95e9-2c85fdd0c511)

**Comment by PKBeam** [comment]
what's your apple music region set to in the settings window?

**Comment by Reynold9650** [comment]
> 您的 Apple Music 區域在設定視窗中設定為什麼？

![image](https://github.com/PKBeam/AMWin-RP/assets/149511905/91d8a9fc-fc89-4e7e-83b6-54683ac9b3ea)

**Comment by PKBeam** [comment]
please post the log files, I'm having trouble reproducing it.

**Comment by Reynold9650** [comment]
[2024-04-25.log](https://github.com/PKBeam/AMWin-RP/files/15108783/2024-04-25.log)

**Comment by PKBeam** [comment]
Fixed by 874c321e, will be in the next release
