### ISSUE TITLE
Song in shown as Now Playing in LastFM but the scrobble is not saved

### ISSUE THREAD

**Issue by Unstriped** [PKBeam/AMWin-RP#99]
**Version Info**
1.4.2 SE - Apple Music 1.4.6.85 (1.1030.21762.0)

**Describe the bug**
After upgrading to 1.4.2 songs are not properly scrobbled. 
The songs shows up as "Now Playing" in LastFm, but after the song has stopped playing it is not saved to my recent tracks.
_edit: the song showing up in "Now Playing" seems to be somewhat inconsistent._ 

Looking in through todays logs I can see that there are issues related to the _SearchSongs() function.

**Log Files**
[2024-04-25.log](https://github.com/PKBeam/AMWin-RP/files/15120290/2024-04-25.log)

**Comment by thefinerarts** [comment]
can confirm.

**Comment by PKBeam** [comment]
same issue as #98

**Comment by thefinerarts** [comment]
Changing the region (from DE) to US unfortunately doesn't resolve #98

**Comment by Unstriped** [comment]
Hi , I appreciate the swift response. Unfortunately the issue persists even after upgrading to 1.4.3. 
I've tried changing my region from SE to US, but it didnt solve the issue for me.

### Version Info
1.4.3 SE / US - Apple Music 1.4.6.85 (1.1030.21762.0

[2024-04-26.log](https://github.com/PKBeam/AMWin-RP/files/15133907/2024-04-26.log)
